version: '3'
services:
  api:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - .:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
